### ISSUE TITLE
Make --no-ansi automatic

### ISSUE THREAD

**Issue by remicollet** [llaville/php-reflect#14]
symfony::console have a method to detect if color are supported (Symfony\Component\Console\Output\StreamOutput::hasColorSupport) and also sebastian/environment.

I think it will be nice to use this method to check if output colors is possible, without having to use the --no-ansi option.

**Comment by llaville** [comment]
@remicollet  New relases Reflect 2.6.2 and CompatInfo 3.7.2 were just published.

I've also pushed source code of new API in branch 3.0 of php-reflect. I've two or three details to fix before to officially published the alpha2 release of Reflect and CompatInfo, but I think you can at least check to see if current behavior match your need !

**Comment by llaville** [comment]
@remicollet Now the source is available, it's just a reminder to do not forget to test if this behavior corresponding to what you are looking for

**Comment by remicollet** [comment]
I just test phpreflect 3.0.0 alpha2 and didn't notice any change.
output is always colored, even when not possible.

Please check how phpunit does, it work perfectly.

**Comment by llaville** [comment]
I didn't understand what is supposed to be (on your side), because I used the standard Synfony Console behavior on color detection and uses.

What command did you used ? Please provide an example (it's always better than a long chat). Thanks in advance

**Comment by remicollet** [comment]
Should not be colored:

      $ phpreflect help | cat

**Comment by remicollet** [comment]
Trivial fix, in Bartlett/Reflect/Console/Application.php

-                $output = new ConsoleOutput();
+                $output  = new StreamOutput(fopen('php://stdout', 'w'));

**Comment by llaville** [comment]
I don't think it's so easy as this. I'm testing a simple console application and I got a big surprise (perharps an issue in Symfony Console). Need to investigate more. I'll keep you aware of results

**Comment by remicollet** [comment]
hmm... in fact issue is because "help" output goes to stderr

So (without modification), this works properly

      $ phpreflect help 2>&1 | cat

**Comment by remicollet** [comment]
So, the question is, why output goes to stderr and not to stdout... (also tested with analyser:run)

**Comment by llaville** [comment]
BTW, you didn't test the `--ouput` option I've introduced to solve compatibily between Linux and Windows that does not collaborate in the same way with the pipe ?

**Comment by remicollet** [comment]
Seems to be a known symfony bug
https://github.com/symfony/symfony/issues/10592

**Comment by llaville** [comment]
The `--no-ansi` option is no more required when using the `--output` option to write results to a file or url.

**Comment by remicollet** [comment]
Sorry but I think --ansi (for "force colors"), and --no-ansi  (for "disable colors") should be kept.

Yes --output is a workaround to have automatic colors detection, but is not always usable (ex: big script running various commands globally redirect to a file)

In all case this is a Symfony issue... so you can close this one (except if you want to apply to proposed workaround).

**Comment by llaville** [comment]
Don't misunderstand. I didn't removed the standard Symfony Console `--no-ansi`. I've just removed it's use combined with the `--output` option what is a specific option of Reflect/CompatInfo Console.

So I'll keep this behavior like it is, if uses want to use it.
