### ISSUE TITLE
sebastian/version 2.0

### ISSUE THREAD

**Issue by remicollet** [llaville/php-reflect#20]
Please allow it

       "sebastian/version": "^1.0 || ^2.0",

AFAIK, No API change

eg: https://github.com/sebastianbergmann/php-code-coverage/commit/95a0e74bc622c55a3aae76fdc9abd89c82fd4bc5

**Comment by llaville** [comment]
Sorry I can't accept yet the major version 2.0 that requires PHP 5.6 min, while Reflect is PHP 5.4 min
See https://github.com/sebastianbergmann/version/blob/master/composer.json#L17

**Comment by llaville** [comment]
Explain already given on https://github.com/llaville/umlwriter/issues/5#issuecomment-180498890
