### ISSUE TITLE
How to use as a library?

### ISSUE THREAD

**Issue by bramus** [llaville/php-reflect#35]
I see that the description for this repo states that `Library that adds the ability to reverse-engineer classes, interfaces, functions, constants and more.` When checking out the documentation however I only find info on the CLI tool.

I'm confused: is there a way to actually use it as a library _(inside another project)_, as a replacement for PHP's built-in `\ReflectionClass`?

**Comment by llaville** [comment]
yes of course. Did you check the examples folder ? And also read the doc ?
BTW new API 5.0 will be different than current 4.x
Even if version 5 was not yet be published as stable, beta 1 is enough stable. Only doc is missing before 5.0 final

**Comment by bramus** [comment]
Yes, but the docs have me bouncing around … [the homepage](http://php5.laurent-laville.org/reflect/) links me to [getting started](http://php5.laurent-laville.org/reflect/manual/current/en/getting-started.html); on there I only see info about the CLI so I click through to [the developer guide](http://php5.laurent-laville.org/reflect/manual/current/en/developer-guide.html). As that's an index page, I continue to the [API Docs](http://php5.laurent-laville.org/reflect/manual/current/en/developer-guide--api.html) but that page also only mention the CLI tool …

A page with info about the “Reflection API” that's being touted [in the features section on the documentation homepage](http://php5.laurent-laville.org/reflect/) would be handy, as that's what I'm looking for. I'll take a peek in the `examples/` folder to see if I can find info in there.

**Comment by llaville** [comment]
@bramus is the examples folder enough for you to know how to process ?

**Comment by bramus** [comment]
I eventually moved to another library, so will be closing this issue as help is no longer needed.

Would recommend to provide some extra documentation in this area though, to retain future users that find this package.

Thanks for the follow-up.
